image: debian:buster

stages:
  - build

before_script:
  - apt-get -y update
  - apt-get -y build-dep .

build_meson:
  stage: build
  tags:
    - librem5
  script:
    - mkdir -p ../build
    - meson ../build/
    - cd ../build
    - ninja install

