image: debian:buster

stages:
  - build
  - test

.tags: &tags
  tags:
    - librem5

before_script:
  - apt-get -y update
  - apt-get -y install wget ca-certificates gnupg
  - echo "deb http://ci.puri.sm/ scratch librem5" > /etc/apt/sources.list.d/ci.list
  - wget -O- https://ci.puri.sm/ci-repo.key | apt-key add -
  - apt-get -y update

build_docs:
  <<: *tags
  stage: build
  artifacts:
    paths:
      - _build
  script:
      - apt-get -y install python3-recommonmark python3-sphinx
      - ./doc/build.sh _build

build_meson:
  <<: *tags
  stage: build
  artifacts:
    paths:
      - _build
    expire_in: 3h
  script:
    - apt-get -y build-dep .
    - meson . _build/ -Ddepdatadir=/usr/share
    - ninja -C _build install

build_deb:
    tags:
        - librem5
    stage: build
    artifacts:
      paths:
        - "*.deb"
    script:
        - rm -f ../*.deb
        - apt-get -y build-dep .
        - apt-get -y install devscripts
        - debuild -i -us -uc -b
        - cp ../*.deb .

build_deb:arm64:
    tags:
        - librem5:arm64
    allow_failure: true
    stage: build
    artifacts:
      paths:
        - "*.deb"
    script:
        - rm -f ../*.deb
        - apt-get -y build-dep .
        - apt-get -y install devscripts
        - debuild -i -us -uc -b
        - cp ../*.deb .

test_lintian:
    <<: *tags
    stage: test
    dependencies:
        - build_deb
    script:
        - apt-get -y install lintian
        - lintian *.deb

test:
  <<: *tags
  stage: test
  needs:
    - build_meson
  script:
    - apt-get -y build-dep .
    - ninja -C _build test
