image: debian:buster

stages:
  - build

before_script:
  - apt-get -y update
  - apt-get -y install wget gnupg2
  - echo "deb http://ci.puri.sm/ scratch librem5" > /etc/apt/sources.list.d/ci.list
  - wget -O- https://ci.puri.sm/ci-repo.key | apt-key add -
  - apt-get -y update
  - apt-get -y build-dep .

build_meson:
  stage: build
  tags:
    - librem5
  script:
    - meson . _build/ -Ddepdatadir=/usr/share
    - ninja -C _build install

