image: debian:buster

stages:
  - build

before_script:
  - apt-get -y update
  - apt-get -y install gnome-common gtk-doc-tools libglib2.0-dev-bin gobject-introspection libglib2.0-dev libpango1.0-dev libgtk-3-dev libxklavier-dev libcroco3-dev

build_automake:
  stage: build
  tags:
    - librem5
  script:
    - ./autogen.sh
    - make
